<h2>Search</h2>
<?php echo $this->tag->form("index/search"); ?>
<p>
    <label for="name">Enter Text </label>
    <?php echo $this->tag->textField("name"); ?>
</p>
<div class="form-check form-check-inline">
    <input class="form-check-input" type="checkbox" id="albums" name="album" />
    <label class="form-check-label" for="albums">Albums</label>
</div>

<div class="form-check form-check-inline">
    <input class="form-check-input" type="checkbox" id="artists" name="artist" />
    <label class="form-check-label" for="artists">Artists</label>
</div>

<div class="form-check form-check-inline">
    <input class="form-check-input" type="checkbox" id="playlist" name="playlist" />
    <label class="form-check-label" for="playlist">playlist</label>
</div>

<div class="form-check form-check-inline">
    <input class="form-check-input" type="checkbox" id="track" name="track" />
    <label class="form-check-label" for="track">track</label>
</div>

<div class="form-check form-check-inline">
    <input class="form-check-input" type="checkbox" id="show" name="show" />
    <label class="form-check-label" for="show">show</label>
</div>

<div class="form-check form-check-inline">
    <input class="form-check-input" type="checkbox" id="episode" name="episode" />
    <label class="form-check-label" for="episode">episode</label>
</div>

<p>
    <?php echo $this->tag->submitButton("Search"); ?>
</p>
</form>