<section class="vh-100 bg-image"
    style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-5">
                            <h2 class="text-uppercase text-center mb-5">Create an account</h2>
                            <?php
                            echo Phalcon\Tag::form(
                                [
                                    "signup/add",
                                    "method" => "post",
                                ]
                            );
                            ?>
                            <div class="form-outline mb-4">
                                <input name='email' type="email" id="form3Example3cg"
                                    class="form-control form-control-lg" />
                                <label class="form-label" for="form3Example3cg">
                                    <?php echo  ("Your Email") ?>
                                </label>
                            </div>

                            <div class="form-outline mb-4">
                                <input name='password' type="password" id="form3Example4cg"
                                    class="form-control form-control-lg" />
                                <label class="form-label" for="form3Example4cg">
                                    <?php echo  ("Password") ?>
                                </label>
                            </div>

                            <div class="form-outline mb-4">
                                <input name='repassword' type="password" id="form3Example4cdg"
                                    class="form-control form-control-lg" />
                                <label class="form-label" for="form3Example4cdg">
                                    <?php echo  ("Repeat your password") ?>
                                </label>
                            </div>
                            <div class="d-flex justify-content-center">
                                <button type="submit"
                                    class="btn btn-primary btn-block btn-lg gradient-custom-4 text-body">
                                    <?php echo  ("Register") ?>
                                </button>
                            </div>
                        </form>
                        <div>
                            <? echo $this->tag->linkTo(
                                ['signup/login',  ('LogIn Instead'), 'class' => 'btn btn-success col-12 mt-2 py-2']
                            );
                            ?>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>